# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 00:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_sidebars', '0002_auto_20160903_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='css_classes',
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='css_id',
        ),
        migrations.AddField(
            model_name='sidebar',
            name='html_classes',
            field=models.TextField(blank=True, help_text='Comma separated list of HTML classes for the sidebar.', null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_\\-\\s,]+$')]),
        ),
        migrations.AddField(
            model_name='sidebar',
            name='html_id',
            field=models.SlugField(blank=True, default=None, help_text='The HTML id to use for the sidebar.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='template',
            field=models.CharField(blank=True, default=None, help_text='Full path to a custom template to use to render this sidebar. If blank the default is used.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(help_text='Title of this sidebar.', max_length=300, unique=True),
        ),
    ]
