# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 00:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_sidebars', '0003_auto_20160904_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='html_classes',
            field=models.TextField(blank=True, help_text='Comma separated list of HTML classes for the sidebar.', null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_\\-\\s,]+$')], verbose_name='HTML classes'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='html_id',
            field=models.SlugField(blank=True, default=None, help_text='The HTML id to use for the sidebar.', max_length=300, null=True, verbose_name='HTML id'),
        ),
    ]
