# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_sidebars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='css_id',
            field=models.SlugField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='css_classes',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_\\-\\s,]+$')]),
        ),
    ]
